name: 'gql pull'
description: 'GraphQL pull'
inputs:
  url:
    description: 'GraphQL endpoint URL'
    required: true

outputs:
  output:
    description: 'Schema difference output'

runs:
  using: 'docker'
  image: 'docker://knabben/gql:latest'
  args:
    - scrape
    - -s
    - ${{ inputs.source }}
    - -d
    - ${{ inputs.destination }}
